### PR TITLE
make: install - remove -D for better cross-platform compatibility fixes #25

### LINKED ISSUE #25: Cannot install on MacOS
Tried:

```
brew install automake
git clone https://github.com/jb55/nostril.git
cd nostril
make install
```

Error: `install: illegal option -- D`

image

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
```install -D``` isn't available on OSs such as macOS and others.

using mkdir -p is more cross-platform friendly.

**Comment by RandyMcMillan** [comment]
fixes  #25

**Comment by kernelkind** [comment]
Was there a reason this wasn't merged? This fix works for me @jb55

**Comment by jb55** [comment]
its a draft so I didn't look at it

**Comment by jb55** [comment]
will merge

**Pull request merged**
